[project]
name = "interviwew-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "bcrypt>=5.0.0",
    "fastapi>=0.124.4",
    "sqlmodel>=0.0.29",
    "typing-extensions>=4.0.0",
    "uvicorn>=0.33.0",
    "python-jose[cryptography]>=3.3.0",
    "langchain>=1.0.0",
    "langchain-openai>=1.0.0",
    "openai>=1.0.0",
    "annotated-doc>=0.0.4",
    "python-dotenv>=1.1.1",
    "websockets>=15.0.1",
    "pydantic-settings>=2.14.0",
    "pymupdf>=1.27.2.3",
]
